# syntax=docker/dockerfile:1.0-experimental
ARG FLAVOR
FROM pyar6329/hie:${FLAVOR} AS hie-cron

RUN set -x && \
  stack --no-terminal update

CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"
